name: live_streaming
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.1.0
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  staggered_grid_view_flutter: ^0.0.4
  url_launcher: ^6.1.10
  flutter_svg: ^1.1.0
  path_provider: ^2.0.9
  http: ^0.13.6

  # for cache network image
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

  share_plus: ^4.5.3



  #  # for local notification
  flutter_local_notifications: 9.4.0
  awesome_notifications: ^0.7.4+1
  firebase_messaging: ^14.7.10

  # google map and geolocator:
  google_places_flutter: ^2.0.7
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_osm_plugin: ^0.60.5
  pointer_interceptor: ^0.10.1
  google_maps_flutter: ^2.5.2



  #loader_overlay:
  loader_overlay: ^4.0.0

  #for responsive UI
  flutter_screenutil: ^5.9.0

  #for shimmer animation
  shimmer: ^3.0.0

  #image pick_or_save
  image_picker: ^1.0.7
  flutter_keyboard_visibility: ^6.0.0


  #device_info_plus:
  device_info_plus: ^9.1.1


  #photo_manager:
  photo_manager: ^3.0.0-dev.5
  photo_manager_image_provider: ^2.1.0

  #video_thumbnail:
  video_thumbnail: ^0.5.3


  #image save
  gallery_saver: ^2.3.2
  image_gallery_saver: ^2.0.3

  #camera:
  camera: ^0.10.5+9

  #connectivity_plus:
  connectivity_plus: ^4.0.0



  #for permission handle:
  permission_handler: ^10.2.0

  # for Calling
  flutter_webrtc: ^0.9.47
  sdp_transform: ^0.3.0
  flutter_ringtone_player: ^3.2.0
  flutter_ion:
    path: ./plugins/ion-app-flutter

  #for signalling
  signalr_netcore: ^1.3.6

  #Logger
  logger: ^1.1.0


  # data store
  path: ^1.8.0
  sqflite: ^2.2.2

  emoji_picker_flutter: 1.5.2

  #native splash
  flutter_native_splash: ^2.2.9

  #for dotted border
  dotted_border: ^2.1.0

  lottie: ^3.0.0
  carousel_slider: ^4.2.1
  keep_screen_on: ^2.0.0
  flutter_foreground_task: ^6.1.2
  fading_edge_scrollview: ^3.0.0

  #page transition
  page_transition: ^2.1.0
  quick_transition: ^0.0.3


  #for screenshot off
  flutter_windowmanager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/language/
    - assets/svg/
    - assets/lottie/
    - assets/
  #    - assets/mobileFaceNet.tflite
  fonts:
    - family: SE Pro Display
      fonts:
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYMEDIUM.OTF
          weight: 600
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYBOLD.OTF
          weight: 800





# run following commands to generate splash screen:
# flutter clean && flutter pub get && flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml

flutter_native_splash:
  #color: "#ffffff"
  background_image: "assets/icons/splash screen.png"
  #image: assets/icons/splashLogo.png
  #branding: "assets/own_logo.png"
  #branding_mode: bottom
  #color_dark: "#000000"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/icons/splashLogo.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    color: "#ffffff"
    #image: assets/icons/splashLogo.png
  #   android_gravity: bottom

  # App icon background color.
  #  icon_background_color: "#111111"

  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'